### ISSUE TITLE
Feature Request: renaming filteres

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#130]
Support with search/replace for vc/ovirt Datacenter renames. The case if where in different systems admins used different names, aga:

ovirt: TestDC
vcenter: TESTDC

Currently it creates slug collision, would be good to being able to merge them by rewriting it for one of the sources.

**Comment by TaLoN1x** [comment]
filtering like with other would work

**Comment by bl4ko** [comment]
So If I understand correctly, you get a slug collision when naming two datacenters the same way (but different case):

```yaml
source:
  - name: TestDC
    type: ovirt
    ...
    
  - name: TESTDC
    type: vcenter
```

This is because the plugin uses common func [`utils.slugify`](https://github.com/bl4ko/netbox-ssot/blob/6b5a477db9232486f896829ebd84759411765069/internal/utils/utils.go#L67), which translates both of the above names to `testdc`.

So you want for slugify function to preserve cases?

**Comment by TaLoN1x** [comment]
Yes, it is correct. With some massive deployments resolving such problems in Hyperviaors might be 'complicated' and take time. A way to rename / remat ClusterGroups would ease onboarding

**Comment by bl4ko** [comment]
Ok understandable, so I can add an option like this in config.yaml:

```
source:
  - name: TestDC
    type: ovirt
    datacenterRename:
      - TestDC = testdc_ov
    
  - name: TESTDC
    type: vcenter
    datacenterRename:
      - TESTDC = testdc_vc
```

or do you suggest something different?
