### ISSUE TITLE
[Bug] asset_tag: device with this asset tag already exists

### ISSUE THREAD

**Issue by broerman** [bl4ko/netbox-ssot#387]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### What is the version of netbox-ssot

Running version v1.7.8 built on 2024-12-18T09:56:47Z (commit 1e7747112e3941dee85c78f168b6ede7f6416d08)

### Which module has the issue?

VMware

### Share your configuration

```yaml
source:                                                                                                                                                                  
  - name: vsphere                                                                                                                                                        
    type: vmware                                                                                                                                                         
                       
    clusterSiteRelations:                                                                                                                                                
      - .*amsap.* = AMSAP                                                                                                                                                
      - .*hamhq.* = HAMHQ                                                                                                                                                
...
...
```

### What is the problem?

Synchronization stops with error
2024/12/23 11:12:15 ERROR   (vsphere): failed to add vmware host Device{Name: amsapsvwit001.gh.de, Type: DeviceType{Manufacturer: VMware, Inc., Model: VMware Virtual Platform}, Role: DeviceRole{Name: Server}, Site: Site{Name: AMSAP}} with error: unexpected status code: 400: {"asset_tag":["device with this asset tag already exists."]}

### Steps to reproduce

1. Start  fresh   netbox-docker  
docker.io/netboxcommunity/netbox:v4.1.9
2. Start Synchronization vsphere  

### What did you expect to happen?

Synchronization should run without errors. 

### What actually happened?

Synchronization stops with error
2024/12/23 11:12:15 ERROR   (vsphere): failed to add vmware host Device{Name: amsapsvwit001.gh.de, Type: DeviceType{Manufacturer: VMware, Inc., Model: VMware Virtual Platform}, Role: DeviceRole{Name: Server}, Site: Site{Name: AMSAP}} with error: unexpected status code: 400: {"asset_tag":["device with this asset tag already exists."]}

### Share your environment details

Docker version 27.3.1, build ce12230
