### ISSUE TITLE
[Bug] failed to open driver: read /dev/ptmx: input/output error

### ISSUE THREAD

**Issue by Geekul** [bl4ko/netbox-ssot#425]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### What is the version of netbox-ssot

v1.8.4

### Which module has the issue?

IOS-XE

### Share your configuration

```yaml
logger:
  level: 0
  dest: ""

netbox:
  apiToken: "xxxxxx"
  hostname: "netbox.example.com"
  httpScheme: https
  port: 443
  timeout: 30
  removeOrphans: false
#  sourcePriority: ["olvm", "prodvmware", "prodprox", "dnacenter", "testvmware", "pa-uk", "fmc-lab"] # Not required, but recommended
source:
  - name: cs2
    type: ios-xe
    hostname: a.b.c.d
    username: netbox
    password: password
    port: 22
#    validateCert: False
#    hostTenantRelations:
#      - .* = MyTenant
#    hostSiteRelations:
#      - .* = MySite
#    vlanTenantRelations:
#      - .* = MyTenant
#    collectArpData:
#      true
```

### What is the problem?

2025/01/22 07:57:01 main.go:102         INFO    (cs2): Initializing source
2025/01/22 07:57:02 main.go:105         ERROR   (cs2): failed to open driver: read /dev/ptmx: input/output error
2025/01/22 07:57:02 main.go:136         INFO    (main): Skipping removing orphaned objects because run failed...
2025/01/22 07:57:02 main.go:146         INFO    (main): ⚠ syncing of source cs2 failed

### Steps to reproduce

docker run -v /path_to/config.yaml:/app/config.yaml ghcr.io/bl4ko/netbox-ssot

### What did you expect to happen?

n/a

### What actually happened?

n/a

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```

### Share your environment details

Ubuntu 24.04
