### ISSUE TITLE
[Bug] `vlanTenantRelations` is not properly assigned to vlans (vmware)

### ISSUE THREAD

**Issue by n-rodriguez** [bl4ko/netbox-ssot#426]
### Is this urgent?

No

### How are you running netbox-ssot?

From source (Go)

### What is the version of netbox-ssot

latest

### Which module has the issue?

General (not module-specific)

### Share your configuration

```yaml
---
logger:
  level: 3
  dest: ""

netbox:
  apiToken: "foo"
  hostname: "netbox.foo.corp"
  httpScheme: http
  port: 80
  timeout: 30
  sourcePriority: ["vcenter67.corp"]
  removeOrphans: false

source:
  - name: vcenter67.corp
    type: vmware
    hostname: vcenter67.corp
    username: administrator@vsphere.local
    password: "password"
    clusterSiteRelations:
      - .* = Foo
    hostSiteRelations:
      - .* = Foo
    clusterTenantRelations:
      - .* = ACME
    hostTenantRelations:
      - .* = ACME
    vmTenantRelations:
      - .* = ACME
    hostRoleRelations:
      - .* = Hypervisor ESX
    vmRoleRelations:
      - .* = Virtual Machine ESX
    vlanTenantRelations:
      - .* = ACME
    vlanSiteRelations:
      - .* = Foo
```

### What is the problem?

`vlanTenantRelations` is not properly assigned to vlans (vmware)

### Steps to reproduce

1. run `netbox-ssot -config ./config.yml`

### What did you expect to happen?

`vlanTenantRelations` is properly assigned to vlans (vmware)

### What actually happened?

`vlanTenantRelations` is not properly assigned to vlans (vmware)

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```
