### ISSUE TITLE
[Bug] don't import vm template (vmware)

### ISSUE THREAD

**Issue by n-rodriguez** [bl4ko/netbox-ssot#429]
### Is this urgent?

No

### How are you running netbox-ssot?

From source (Go)

### What is the version of netbox-ssot

latest

### Which module has the issue?

General (not module-specific)

### Share your configuration

```yaml
---
logger:
  level: 3
  dest: ""

netbox:
  apiToken: "foo"
  hostname: "netbox.foo.corp"
  httpScheme: http
  port: 80
  timeout: 30
  sourcePriority: ["vcenter67.corp"]
  removeOrphans: false

source:
  - name: vcenter67.corp
    type: vmware
    hostname: vcenter67.corp
    username: administrator@vsphere.local
    password: "password"
    clusterSiteRelations:
      - .* = Foo
    hostSiteRelations:
      - .* = Foo
    clusterTenantRelations:
      - .* = ACME
    hostTenantRelations:
      - .* = ACME
    vmTenantRelations:
      - .* = ACME
    hostRoleRelations:
      - .* = Hypervisor ESX
    vmRoleRelations:
      - .* = Virtual Machine ESX
    vlanTenantRelations:
      - .* = ACME
    vlanSiteRelations:
      - .* = Foo
```

### What is the problem?

`netbox-ssot` imports VMware VM templates

### Steps to reproduce

1. run `netbox-ssot -config ./config.yml`

### What did you expect to happen?

`netbox-ssot` should not import VMware VM templates

### What actually happened?

`netbox-ssot` imports VMware VM templates

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```

**Comment by bl4ko** [comment]
I have added config option for the vmware source to filterout vm templates:

```
source:
  - name: vcenter67.corp
    type: vmware
    ...
    ignoreVMTemplates: True
```
