### ISSUE TITLE
[Bug] The specified disk size (26843) must match the aggregate size of assigned virtual disks (25000).

### ISSUE THREAD

**Issue by n-rodriguez** [bl4ko/netbox-ssot#430]
### Is this urgent?

No

### How are you running netbox-ssot?

From source (Go)

### What is the version of netbox-ssot

latest

### Which module has the issue?

General (not module-specific)

### Share your configuration

```yaml
---
logger:
  level: 3
  dest: ""

netbox:
  apiToken: "foo"
  hostname: "netbox.foo.corp"
  httpScheme: http
  port: 80
  timeout: 30
  sourcePriority: ["vcenter67.corp"]
  removeOrphans: false

source:
  - name: vcenter67.corp
    type: vmware
    hostname: vcenter67.corp
    username: administrator@vsphere.local
    password: "password"
    clusterSiteRelations:
      - .* = Foo
    hostSiteRelations:
      - .* = Foo
    clusterTenantRelations:
      - .* = ACME
    hostTenantRelations:
      - .* = ACME
    vmTenantRelations:
      - .* = ACME
    hostRoleRelations:
      - .* = Hypervisor ESX
    vmRoleRelations:
      - .* = Virtual Machine ESX
    vlanTenantRelations:
      - .* = ACME
    vlanSiteRelations:
      - .* = Foo
```

### What is the problem?

`netbox-ssot` failed to update VM config

### Steps to reproduce

1. run `netbox-ssot -config ./config.yml`

### What did you expect to happen?

`netbox-ssot` should have successfully updated VM config

### What actually happened?

`netbox-ssot` failed to update VM config

### Share DEBUG-level logs (remove sensitive information)

```plaintext
failed to sync vmware VM foo.bar: unexpected status code: 400: {"disk":["The specified disk size (26843) must match the aggregate size of assigned virtual disks (25000)."]
failed to sync vmware VM baz.bar: unexpected status code: 400: {"disk":["The specified disk size (16106) must match the aggregate size of assigned virtual disks (15000)."]}
```
