### ISSUE TITLE
[Bug] fmc initialization failure

### ISSUE THREAD

**Issue by Geekul** [bl4ko/netbox-ssot#432]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### What is the version of netbox-ssot

1.8.4

### Which module has the issue?

FMC

### Share your configuration

```yaml
source:
  - name: fmc
    type: fmc
    hostname: fmcv.example.com
    username: user
    password: password
    validateCert: True
    hostTenantRelations:
      - .* = MyTenant
    hostSiteRelations:
      - .* = MySite
    vlanTenantRelations:
      - .* = MyTenant
```

### What is the problem?

 main.go:105         ERROR   (fmc): fmc initialization failure: init devices: error initializing vlan interfaces: error getting vlan interfaces: make request for VLAN interfaces: unexpected status code: 405

### Steps to reproduce

docker run -v /path_to/config.yaml:/app/config.yaml ghcr.io/bl4ko/netbox-ssot

### What did you expect to happen?

n/a

### What actually happened?

n/a

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```

### Share your environment details

Ubuntu 24.04
