### ISSUE TITLE
[Bug] mac address

### ISSUE THREAD

**Issue by Geekul** [bl4ko/netbox-ssot#451]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### What is the version of netbox-ssot

latest: main or develop tag

### Which module has the issue?

IOS-XE

### Share your configuration

```yaml
ource:
  - name: MLS-DC
    type: ios-xe
    hostname: a.b.c.d
    username: user
    password: pass
    port: 830
    validateCert: False
    hostTenantRelations:
      - .* = MyTenant
    hostSiteRelations:
      - .* = DC
    vlanTenantRelations:
      - .* = MyTenant
    collectArpData:
      true
```

### What is the problem?

2025/01/31 11:29:44 main.go:117         ERROR   (MLS-DC): create mac address for object type: add mac address MACAddress{MAC: 00:D6:FE:25:D9:06}: unexpected status code: 400: {"assigned_object_id":["This field cannot be null."]}
2025/01/31 11:29:44 main.go:136         INFO    (main): Skipping removing orphaned objects because run failed...

### Steps to reproduce

docker run

### What did you expect to happen?

n/n

### What actually happened?

n/a

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```

### Share your environment details

Ubuntu 24.04
